title: Full Japanese Study Deck
baseurl: "/Full-Japanese-Study-Deck"
url: "https://ronokof.github.io"

# Site info
titleabbr: "FJSD"
ogdescription: "A Comprehensive Anki Deck Covering Kana, Core & JLPT Vocabulary, Kanji & Grammar + Extra Vocab/Kanji"
keywords: "fjsd, japanese, japanese-language, japanese-learning, anki-cards, anki-deck, anki, katakana, hiragana, kana, kanji, japanese-grammar, jlpt, core, henkan"
author: "Ronokof"
email: "ronokoffjsd@gmail.com"

# Google info
googlesearchkey: "83Fd3Sc9pWlvuRTKwxjKfSBHmYhaM5rCMX9Yxen8oIg"
googleanalyticsid: "G-1VTT4LZ48H"

# Asset paths
bannerpath: "/assets/fjsd.png"
kanapath: "/assets/kana.png"
kanjipath: "/assets/kanji.png"
radicalpath: "/assets/radical.png"
wordpath: "/assets/word.png"
grammarpath: "/assets/grammar.png"

# Anki deck entries count
kana: "142"
kanaextended: "230"
corevocab: "10,012"
corekanji: "2,216"
grammar: "644"
radicals: "261"
kanaonlywords: "5,822"
extrakanji: "558"
extrakanjiwords: "28,229"

# Anki deck info
deckversion: "10.2"
