import path from "path";
import { NoteTypes, SubDeckNames } from "./utils";

export const deckName: string = 'Full Japanese Study Deck [JLPT N5~N1 vocab/kanji + common vocab and kanji + grammar]';

export const subDeckNames: SubDeckNames = {
	kana: {
		'_': '0. Kana',
		hiragana: 'Hiragana',
		hiraganaExtended: 'Hiragana extended',
		katakana: 'Katakana',
		katakanaExtended: 'Katakana extended'
	},
	jlpt: {
		'_': '1. JLPT',
		kanji: {
			'_': 'Kanji',
			n5: 'N5',
			n4: 'N4',
			n3: 'N3',
			n2: 'N2',
			n1: 'N1'
		},
		vocab: {
			'_': 'Vocab',
			n5: 'N5',
			n4: 'N4',
			n3: 'N3',
			n2: 'N2',
			n1: 'N1'
		}
	},
	grammar: {
		'_': '2. Grammar',
		n5: 'N5',
		n4: 'N4',
		n3: 'N3',
		n2: 'N2',
		n1: 'N1',
		additional: 'Additional'
	},
	radicals: { '_': '3. Kanji radicals (reference)' },
	kanaWords: { '_': '4. Vocab with no kanji (mining/reference)' },
	extraKanji: {
		'_': '5. Extra kanji (mining/reference)',
		kanji: 'Kanji',
		vocab: 'Vocab'
	}
}

export const noteTypes: NoteTypes = {
	grammar: 'Grammar',
	kana: 'Kana',
	kanji: 'Kanji',
	radical: 'Radical',
	word: 'Word'
}

export const dictsDir: string = path.resolve('./dicts');
export const svgDir: string = path.resolve('./svgs');
export const kanjiInfoFile: string = path.resolve('./results/kanji-info.json');
export const radicalInfoFile: string = path.resolve('./results/radical-info.json');

export const dictsNames: { jmdict: string, kanjidic: string, tanaka: string, radk: string, krad: string } = {
	jmdict: 'JMdict_e',
	kanjidic: 'kanjidic2',
	tanaka: 'tanaka_examples',
	radk: 'radkfile2',
	krad: 'kradfile2'
}

export const fileNames: { kana: string[], vocabJLPT: string[], kanjiJLPT: string[], grammar: string[] } = {
	kana: ['hiragana', 'hiragana_extended', 'katakana', 'katakana_extended'],
	vocabJLPT: ['vocab_n5', 'vocab_n4', 'vocab_n3', 'vocab_n2', 'vocab_n1'],
	kanjiJLPT: ['kanji_n5', 'kanji_n4', 'kanji_n3', 'kanji_n2', 'kanji_n1'],
	grammar: ['grammar_n5', 'grammar_n4', 'grammar_n3', 'grammar_n2', 'grammar_n1', 'grammar_additional']
}

export const resultPaths: { vocabJLPT: string, kanjiJLPT: string, radicals: string, kana: string, grammar: string, extraKanji: string, kanaWords: string } = {
	vocabJLPT: path.resolve('./results/vocabJLPT'),
	kanjiJLPT: path.resolve('./results/kanjiJLPT'),
	radicals: path.resolve('./results/radicals'),
	kana: path.resolve('./results/kana'),
	grammar: path.resolve('./results/grammar'),
	extraKanji: path.resolve('./results/extra-kanji'),
	kanaWords: path.resolve('./results/kana-words')
};

export const regexps: { hiragana: RegExp, katakana: RegExp, kanji: RegExp, scriptSplit: RegExp, regExChars: RegExp, tanakaID: RegExp, tanakaPart: RegExp, tanakaReferenceID: RegExp } = {
	hiragana: /[\u{3040}-\u{309F}]/u,
	katakana: /[\u{30A0}-\u{30FF}]/u,
	kanji: /([\u{4E00}-\u{9FFF}\u{3400}-\u{4DBF}\u{20000}-\u{2A6DF}\u{2A700}-\u{2B73F}\u{2B740}-\u{2B81F}\u{2B820}-\u{2CEA1}\u{2CEB0}-\u{2EBE0}\u{30000}-\u{3134A}\u{31350}-\u{323AF}\u{2EBF0}-\u{2EE5F}\u{F900}-\u{FAFF}\u{2F800}-\u{2FA1F}]{1})/u,
	scriptSplit: /([\p{sc=Han}]+|[\p{sc=Hiragana}]+|[\p{sc=Katakana}]+|[^\p{sc=Han}\p{sc=Hiragana}\p{sc=Katakana}]+)/u,
	regExChars: /[-\/\\^$*+?.()|[\]{}]/,
	tanakaID: /#ID=\d+_\d+$/,
	tanakaPart: /(?<base>[^()\[\]\{\}\s]+)(?:\((?<reading>[\S]+)\))?(?:\[(?<glossnum>[\S]+)\])?(?:\{(?<inflection>[\S]+)\})?/,
	tanakaReferenceID: /#([\d]+)/
};

export const notSearchedForms: Set<string> = new Set<string>([
	'Search-only kana form',
	'Rarely used kana form',
	'Out-dated or obsolete kana usage',
	'Word containing out-dated kanji or kanji usage'
]);

export const noteMap: Map<string, string> = new Map<string, string>([
	["dialect: brazilian", "dialect::brazilian"],
	["dialect: hokkaido-ben", "dialect::hokkaido-ben"],
	["dialect: kansai-ben", "dialect::kansai-ben"],
	["dialect: kantou-ben", "dialect::kantou-ben"],
	["dialect: kyoto-ben", "dialect::kyoto-ben"],
	["dialect: kyuushuu-ben", "dialect::kyuushuu-ben"],
	["dialect: nagano-ben", "dialect::nagano-ben"],
	["dialect: ryuukyuu-ben", "dialect::ryuukyuu-ben"],
	["dialect: osaka-ben", "dialect::osaka-ben"],
	["dialect: touhoku-ben", "dialect::touhoku-ben"],
	["dialect: tosa-ben", "dialect::tosa-ben"],
	["dialect: tsugaru-ben", "dialect::tsugaru-ben"],
	["adjective (keiyoushi)", "adjective::i"],
	["'taru' adjective", "adjective::taru"],
	["noun (common) (futsuumeishi)", "noun"],
	["pre-noun adjectival (rentaishi)", "pre-noun_adjectival"],
	["noun or verb acting prenominally", "noun_or_verb_acting_prenominally"],
	["pronoun", "pronoun"],
	["adverb (fukushi)", "adverb"],
	["adverb taking the 'to' particle", "takes::to"],
	["onomatopoeic or mimetic word", "onomatopoeic_or_mimetic"],
	["nouns which may take the genitive case particle 'no'", "takes::no"],
	["noun or participle which takes the aux. verb suru", "takes::suru"],
	["suru verb - irregular", "suru_verb"],
	["suru verb - special class", "suru_verb"],
	["ichidan verb", "ichidan_verb"],
	["godan verb with 'ku' ending", "godan::ku::verb"],
	["godan verb with 'gu' ending", "godan::gu::verb"],
	["godan verb with 'u' ending", "godan::u::verb"],
	["godan verb with 'tsu' ending", "godan::tsu::verb"],
	["godan verb with 'ru' ending", "godan::ru::verb"],
	["godan verb with 'nu' ending", "godan::nu::verb"],
	["godan verb with 'mu' ending", "godan::mu::verb"],
	["godan verb with 'bu' ending", "godan::bu::verb"],
	["godan verb with 'su' ending", "godan::su::verb"],
	["godan verb with 'u' ending (special class)", "godan::u::irregular_verb"],
	["godan verb with 'ru' ending (irregular verb)", "godan::ru::irregular_verb"],
	["godan verb - -aru special class", "godan::aru::irregular_verb"],
	["godan verb - iku/yuku special class", "godan::iku_yuku::irregular_verb"],
	["irregular nu verb", "godan::nu::irregular_verb"],
	["kuru verb - special class", "kuru_verb"],
	["transitive verb", "transitive_verb"],
	["intransitive verb", "intransitive_verb"],
	["auxiliary verb", "auxiliary_verb"],
	["auxiliary adjective", "adjective::auxiliary"],
	["auxiliary", "auxiliary"],
	["after a verb", "after::verb"],
	["after the -te form of a verb", "after::te_form"],
	["after te-form of verbs and adj.", "after::verb_or_adjective_te_form"],
	["after the -masu stem of a verb", "after::masu_stem"],
	["after -masu stem of verb", "after::masu_stem"],
	["after masu stem of verb", "after::masu_stem"],
	["after -masu stem or adj. stem", "after::masu_or_adjective_stem"],
	["after a noun or the -masu stem of a verb", "after::noun_or_masu_stem"],
	["after the plain past form of a verb", "after::plain_or_past_verb_form"],
	["after present form of a verb", "after::plain_verb_form"],
	["after the dictionary form of a verb", "after::plain_verb_form"],
	["after past form of a verb", "after::past_verb_form"],
	["after volitional form of verb", "after::volitional_verb_form"],
	["after the past tense form of a verb", "after::past_verb_form"],
	["after adjective stem", "after::adjective_stem"],
	["with neg. sentence", "with::negative_verb"],
	["with neg. verb", "with::negative_verb"],
	["with. neg. verb", "with::negative_verb"],
	["with a verb in negative form", "with::negative_verb"],
	["with verb in the negative", "with::negative_verb"],
	["with negative verb", "with::negative_verb"],
	["after negative base of verb", "with::negative_verb"],
	["follows a verb in \"-te\" form", "after::te_form"],
	["before a verb in negative form", "before::negative_verb"],
	["before a negative form", "before::negative_verb"],
	["before a neg. form", "before::negative_verb"],
	["before a noun or a verb", "before::noun_or_verb"],
	["before an adjective", "before::adjective"],
	["after a noun", "after::noun"],
	["prefix", "prefix"],
	["noun, used as a prefix", "prefix_noun"],
	["suffix", "suffix"],
	["noun, used as a suffix", "suffix_noun"],
	["counter", "counter"],
	["numeric", "numeric"],
	["particle", "particle"],
	["conjunction", "conjunction"],
	["expression", "expression"],
	["idiomatic expression", "idiomatic_expression"],
	["interjection (kandoushi)", "interjection"],
	["proverb", "proverb"],
	["yojijukugo", "yojijukugo"],
	["archaism", "archaism"],
	["obsolete term", "obsolete"],
	["dated term", "dated"],
	["rare", "rare"],
	["colloquialism", "colloquialism"],
	["slang", "slang"],
	["internet slang", "internet_slang"],
	["jocular, humorous term", "jocular_humorous"],
	["vulgar expression or word", "vulgar"],
	["derogatory", "derogatory"],
	["sensitive", "sensitive"],
	["euphemistic", "euphemistic"],
	["abbreviation", "abbreviation"],
	["male term or language", "male_language"],
	["female term or language", "female_language"],
	["honorific or respectful (sonkeigo) language", "sonkeigo"],
	["polite (teineigo) language", "teineigo"],
	["humble (kenjougo) language", "kenjougo"],
	["familiar language", "familiar_language"],
	["familiar or derogatory", "familiar_or_derogatory"],
	["derogatory or familiar", "familiar_or_derogatory"],
	["children's language", "children_language"],
	["formal or literary term", "formal_or_literary"],
	["usually written using kana alone", "usually_in_kana"],
	["ateji (phonetic) reading", "ateji"],
	["rarely-used kanji form", "rare_kanji_form"],
	["out-dated kanji", "out-dated_kanji_form"],
	["gikun (meaning as reading) or jukujikun (special kanji reading)", "gikun_or_jukujikun"],
	["irregular okurigana usage", "irregular::okurigana"],
	["irregular kana usage", "irregular::kana"],
	["word containing irregular kana usage", "irregular::kana"],
	["out-dated or obsolete kana usage", "out-dated_or_obsolete_kana"],
	["irregular kanji", "irregular::kanji_form"],
	["irreg. kanji form", "irregular::kanji_form"],
	["mathematics term", "mathematics"],
	["computer terminology", "computer_terminology"],
	["buddhist term", "buddhism"],
	["physics terminology", "physics"],
	["food term", "food"],
	["chemistry term", "chemistry"],
	["historical term", "historical"],
	["grammar", "grammar"],
	["martial arts term", "martial_arts"],
	["linguistics terminology", "linguistics"],
	["sports term", "sports"],
	["sumo term", "sumo"],
	["astronomy term", "astronomy"],
	["baseball term", "baseball"],
	["biology term", "biology"],
	["shogi term", "shogi"],
	["logic", "logic"],
	["medicine term", "medicine"],
	["music", "music"],
	["music term", "music"],
	["geology", "geology"],
	["meteorology", "meteorology"],
	["shinto term", "shinto"],
	["christianity", "christianity"],
	["finance term", "finance"],
	["economics term", "economics"],
	["business term", "business"],
	["statistics", "statistics"],
	["anatomical term", "anatomical"],
	["genetics", "genetics"],
	["engineering term", "engineering"],
	["architecture term", "architecture"],
	["paleography term", "paleography"],
	["psychiatry", "psychiatry"],
	["law term", "law"],
	["military term", "military"],
	["mahjong term", "mahjong"],
	["philosophy", "philosophy"],
	["physiology", "physiology"],
	["zoology term", "zoology"],
	["card games", "card_games"],
	["hanafuda", "hanafuda"],
	["go (game)", "go"],
	["golf", "golf"],
	["fishing", "fishing"],
	["on-yomi, go", "on-yomi::go"],
	["on-yomi, kan", "on-yomi::kan"],
	["on-yomi, kan\\'you", "on-yomi::kanyou"],
	["kun-yomi", "kun-yomi"],
	["reading used only in names (nanori)", "nanori"],
	["on-yomi", "on-yomi"],
	["reading used as name of radical", "radical_reading"],
	["rarely used kana form", "rare_kana_form"],
	["search-only kana form", "search-only_kana_form"],
	["on-yomi, tou", "on-yomi::tou"],
	["irregular kanji usage", "irregular::kanji_form"],
	["word containing irregular kanji usage", "irregular::kanji_form"],
	["out-dated kanji or kanji usage", "out-dated_kanji_form"],
	["word containing out-dated kanji or kanji usage", "out-dated_kanji_form"],
	["rarely used kanji form", "rare_kanji_form"],
	["search-only kanji form", "search-only_kanji_form"],
	["aphorism (pithy saying)", "aphorism"],
	["archaic", "archaism"],
	["character", "character"],
	["colloquial", "colloquialism"],
	["company name", "company_name"],
	["creature", "creature"],
	["deity", "deity"],
	["document", "document"],
	["event", "event"],
	["female term, language, or name", "female_language"],
	["fiction", "fiction"],
	["given name or forename, gender not specified", "given_name_or_forename"],
	["group", "group"],
	["legend", "legend"],
	["manga slang", "manga_slang"],
	["male term, language, or name", "male_language"],
	["mythology", "mythology"],
	["object", "object"],
	["organization name", "organization_name"],
	["other", "other"],
	["full name of a particular person", "full_name_or_particular_person"],
	["place name", "place_name"],
	["poetical term", "poetical"],
	["product name", "product_name"],
	["quotation", "quotation"],
	["rare term", "rare"],
	["religion", "religion"],
	["service", "service"],
	["ship name", "ship_name"],
	["railway station", "railway"],
	["family or surname", "family_or_surname"],
	["word usually written using kana alone", "usually_in_kana"],
	["unclassified name", "unclassified"],
	["work of art, literature, music, etc. name", "work_of_art"],
	["rude or x-rated term (not displayed in educational software)", "rude_or_x-rated"],
	["adjective (keiyoushi)", "adjective"],
	["adjective (keiyoushi) - yoi/ii class", "adjective::yoi/ii"],
	["'kari' adjective (archaic)", "adjective::kari"],
	["'ku' adjective (archaic)", "adjective::ku"],
	["adjectival nouns or quasi-adjectives (keiyodoshi)", "adjectival_nouns_or_quasi-adjectives"],
	["archaic/formal form of na-adjective", "na-adjective_archaic_or_formal"],
	["nouns which may take the genitive case particle 'no'", "noun_takes_no"],
	["'shiku' adjective (archaic)", "adjective::shiku"],
	["copula", "copula"],
	["expressions (phrases, clauses, etc.)", "expression"],
	["noun (common) (futsuumeishi)", "common_noun"],
	["adverbial noun (fukushitekimeishi)", "adverbial_noun"],
	["proper noun", "proper_noun"],
	["noun (temporal) (jisoumeishi)", "temporal_noun"],
	["unclassified", "unclassified"],
	["verb unspecified", "unspecified_verb"],
	["ichidan verb - kureru special class", "ichidan_verb::kureru"],
	["nidan verb with 'u' ending (archaic)", "nidan_verb::u"],
	["nidan verb (upper class) with 'bu' ending (archaic)", "nidan_verb::bu::upper_class"],
	["nidan verb (lower class) with 'bu' ending (archaic)", "nidan_verb::bu::lower_class"],
	["nidan verb (upper class) with 'dzu' ending (archaic)", "nidan_verb::dzu::upper_class"],
	["nidan verb (lower class) with 'dzu' ending (archaic)", "nidan_verb::dzu::lower_class"],
	["nidan verb (upper class) with 'gu' ending (archaic)", "nidan_verb::gu::upper_class"],
	["nidan verb (lower class) with 'gu' ending (archaic)", "nidan_verb::gu::lower_class"],
	["nidan verb (upper class) with 'hu/fu' ending (archaic)", "nidan_verb::hu/fu::upper_class"],
	["nidan verb (lower class) with 'hu/fu' ending (archaic)", "nidan_verb::hu/fu::lower_class"],
	["nidan verb (upper class) with 'ku' ending (archaic)", "nidan_verb::ku::upper_class"],
	["nidan verb (lower class) with 'ku' ending (archaic)", "nidan_verb::ku::lower_class"],
	["nidan verb (upper class) with 'mu' ending (archaic)", "nidan_verb::mu::upper_class"],
	["nidan verb (lower class) with 'mu' ending (archaic)", "nidan_verb::mu::lower_class"],
	["nidan verb (lower class) with 'nu' ending (archaic)", "nidan_verb::nu::lower_class"],
	["nidan verb (upper class) with 'ru' ending (archaic)", "nidan_verb::ru::upper_class"],
	["nidan verb (lower class) with 'ru' ending (archaic)", "nidan_verb::ru::lower_class"],
	["nidan verb (lower class) with 'su' ending (archaic)", "nidan_verb::su::lower_class"],
	["nidan verb (upper class) with 'tsu' ending (archaic)", "nidan_verb::tsu::upper_class"],
	["nidan verb (lower class) with 'tsu' ending (archaic)", "nidan_verb::tsu::lower_class"],
	["nidan verb (lower class) with 'u' ending and 'we' conjugation (archaic)", "nidan_verb::u_with_we_conjugation::lower_class"],
	["nidan verb (upper class) with 'yu' ending (archaic)", "nidan_verb::yu::upper_class"],
	["nidan verb (lower class) with 'yu' ending (archaic)", "nidan_verb::yu::lower_class"],
	["nidan verb (lower class) with 'zu' ending (archaic)", "nidan_verb::zu::lower_class"],
	["yodan verb with 'bu' ending (archaic)", "yodan_verb::bu"],
	["yodan verb with 'gu' ending (archaic)", "yodan_verb::gu"],
	["yodan verb with 'hu/fu' ending (archaic)", "yodan_verb::hu/fu"],
	["yodan verb with 'ku' ending (archaic)", "yodan_verb::ku"],
	["yodan verb with 'mu' ending (archaic)", "yodan_verb::mu"],
	["yodan verb with 'nu' ending (archaic)", "yodan_verb::nu"],
	["yodan verb with 'ru' ending (archaic)", "yodan_verb::ru"],
	["yodan verb with 'su' ending (archaic)", "yodan_verb::su"],
	["yodan verb with 'tsu' ending (archaic)", "yodan_verb::tsu"],
	["godan verb - -aru special class", "godan::aru::irregular_verb"],
	["godan verb - uru old class verb (old form of eru)", "godan::uru::irregular_verb"],
	["irregular ru verb, plain form ends with -ri", "irregular_ru_verb_plain_form_ending_with_ri"],
	["noun or participle which takes the aux. verb suru", "noun_or_participle_taking_suru"],
	["su verb - precursor to the modern suru", "su_verb"],
	["suru verb - included", "suru_verb"],
	["ichidan verb - zuru verb (alternative form of -jiru verbs)", "ichidan_verb::zuru"],
	["agriculture", "agriculture"],
	["anatomy", "anatomical"],
	["archeology", "archeology"],
	["architecture", "architecture"],
	["art, aesthetics", "art/aesthetics"],
	["astronomy", "astronomy"],
	["audiovisual", "audiovisual"],
	["aviation", "aviation"],
	["baseball", "baseball"],
	["biochemistry", "biochemistry"],
	["biology", "biology"],
	["botany", "botany"],
	["boxing", "boxing"],
	["buddhism", "buddhism"],
	["business", "business"],
	["chemistry", "chemistry"],
	["chinese mythology", "mythology::chinese"],
	["civil engineering", "civil_engineering"],
	["clothing", "clothing"],
	["computing", "computing"],
	["crystallography", "crystallography"],
	["dentistry", "dentistry"],
	["ecology", "ecology"],
	["economics", "economics"],
	["electricity, elec. eng.", "electricity"],
	["electronics", "electronics"],
	["embryology", "embryology"],
	["engineering", "engineering"],
	["entomology", "entomology"],
	["figure skating", "figure_skating"],
	["film", "film"],
	["finance", "finance"],
	["food, cooking", "food"],
	["gardening, horticulture", "gardening"],
	["geography", "geography"],
	["geometry", "geometry"],
	["greek mythology", "mythology::greek"],
	["horse racing", "horse_racing"],
	["internet", "internet"],
	["japanese mythology", "mythology::japanese"],
	["kabuki", "kabuki"],
	["law", "law"],
	["linguistics", "linguistics"],
	["martial arts", "martial_arts"],
	["mahjong", "mahjong"],
	["manga", "manga"],
	["mathematics", "mathematics"],
	["mechanical engineering", "mechanical_engineering"],
	["medicine", "medicine"],
	["military", "military"],
	["mineralogy", "mineralogy"],
	["mining", "mining"],
	["motorsport", "motorsport"],
	["noh", "noh"],
	["ornithology", "ornithology"],
	["paleontology", "paleontology"],
	["pathology", "pathology"],
	["pharmacology", "pharmacology"],
	["photography", "photography"],
	["physics", "physics"],
	["politics", "politics"],
	["printing", "printing"],
	["professional wrestling", "professional_wrestling"],
	["psychoanalysis", "psychoanalysis"],
	["psychology", "psychology"],
	["railway", "railway"],
	["roman mythology", "mythology::roman"],
	["shinto", "shinto"],
	["shogi", "shogi"],
	["skiing", "skiing"],
	["sports", "sports"],
	["stock market", "stock_market"],
	["sumo", "sumo"],
	["surgery", "surgery"],
	["telecommunications", "telecommunications"],
	["trademark", "trademark"],
	["television", "television"],
	["veterinary terms", "veterinary"],
	["video games", "video_games"],
	["zoology", "zoology"],
	["equivalent", "equivalent"],
	["explanatory", "explanatory"],
	["figuratively", "figuratively"],
	["literally", "literally"],
	["aichi dialect", "aichi"],
	["botany term", "botany"],
	["edo-period term", "edo-period"],
	["geology term", "geology"],
	["geometry term", "geometry"],
	["heian-period term", "heian-period"],
	["imperial japanese army jargon", "imperial_japanese_army_jargon"],
	["meiji and taishō-era term", "meiji_and_taishou_era"],
	["tochigi dialect", "tochigi"],
	["after -masu base of verb; indicates contempt or disdain for another's actions", "after::masu_stem"],
	["after -masu stem of verb; indicates an action is being directed to someone", "after::masu_stem"],
	["after -masu stem of verb; often ぐるしい", "after::masu_stem"],
	["after -masu stems, onomatopoeic and mimetic words", "after::masu_stem"],
	["after a -masu stem, esp. of a suru verb", "after::masu_stem"],
	["after a -nai stem", "after::nai_stem"],
	["after a name", "after::name"],
	["after a noun (+ の)", "after::noun"],
	["after a noun at the end of an interjection", "after::noun"],
	["after a noun indicating a person", "after::noun"],
	["after a noun or -masu stem", "after::noun_or_masu_stem"],
	["after a noun or counter", "after::noun_or_counter"],
	["after a noun or na-adjective; in conditional clauses", "after::noun_or_na-adjective"],
	["after a noun or pronoun", "after::noun_or_pronoun"],
	["after a noun, adverb or adj. stem", "after::noun_adverb_or_adjective_stem"],
	["after a number n", "after::number"],
	["after a number of people", "after::number_of_people"],
	["after a number or counter", "after::number_or_counter"],
	["after a quantity", "after::quantity"],
	["after a quantity, age, time, etc.", "after::quantity"],
	["after a surname", "after::surname"],
	["after a time, date, etc.", "after::time_date"],
	["after a verb in the past tense", "after::past_verb_form"],
	["after a volitional form", "after::volitional_verb_form"],
	["after an adjective, verb, or noun", "after::adjective_verb_or_noun"],
	["after an adverb", "after::adverb"],
	["after an age", "after::age"],
	["after an interrogative", "after::interrogative"],
	["after conditional -ba form of verb", "after::conditional_ba_verb_form"],
	["after dictionary form verb", "after::plain_verb_form"],
	["after neg. verb", "with::negative_verb"],
	["after negative verb", "with::negative_verb"],
	["after past tense verb", "after::past_verb_form"],
	["after plain form of a verb or adjective", "after::plain_verb_or_adjective_form"],
	["after the -nai stem of a verb", "after::nai_stem"],
	["after the -ta form of a verb", "after::past_verb_form"],
	["after the -te form of a verb or adjective", "after::te_verb_or_adjective_form"],
	["after the dictionary form of verb", "after::plain_verb_form"],
	["after the stem of an adjective", "after::adjective_stem"],
	["after the volitional form of verb", "after::volitional_verb_form"],
	["at sentence end", "at_sentence_end"],
	["at sentence end after the -masu form of a verb", "at_sentence_end"],
	["at sentence end after the question marker か", "at_sentence_end"],
	["at sentence end; adds emphasis; usu. ったら", "at_sentence_end"],
	["at sentence end; expresses depth of feeling or emphasis", "at_sentence_end"],
	["at sentence end; gives reason for an unstated but deducible conclusion", "at_sentence_end"],
	["at sentence end; used as a request for confirmation or agreement", "at_sentence_end"],
	["at sentence end; used to express one's thoughts or feelings", "at_sentence_end"],
	["at sentence end; used to make a sentence threatening or ironic", "at_sentence_end"],
	["at sentence end; used to make an informal request", "at_sentence_end"],
	["at sentence end; with a negative", "at_sentence_end"],
	["at sentence-end", "at_sentence_end"],
	["at sentence-end; indicates certainty, emphasis, contempt, request, warning, etc.", "at_sentence_end"],
	["at sentence-end; indicates certainty, emphasis, etc.", "at_sentence_end"],
	["at start of sentence", "at_sentence_start"],
	["at the start of a sentence", "at_sentence_start"],
	["before a noun", "before::noun"],
	["before a verb", "before::verb"],
	["emphatic", "emphatic"],
	["fig.", "figurative"],
	["figurative", "figurative"],
	["followed by a counter", "after::counter"],
	["followed by a counter and か", "after::counter"],
	["followed by a verb in negative form", "after::negative_verb"],
	["following adj. stem", "after::adjective_stem"],
	["following adj. stem or noun", "after::adjective_stem_or_noun"],
	["following the te-form of a verb", "after::te_form"],
	["follows verbs, adjectives", "after::verb_or_adjective"],
	["formal or literary polite copula", "formal_or_literary_polite_copula"],
	["general term", "general"],
	["in a negative sentence", "with::negative_verb"],
	["literal meaning", "literally"],
	["non-standard", "non-standard"],
	["non-standard usage", "non-standard"],
	["orig. meaning", "original_meaning"],
	["original meaning", "original_meaning"],
	["plain copula", "plain_copula"],
	["sentence end, mainly masc.", "at_sentence_end"],
	["sentence final", "at_sentence_end"],
	["vocative", "vocative"],
	["with a verb in the negative", "with::negative_verb"],
	["with an interrogative word", "with::interrogative"],
	["with neg. verb or adjective", "with::negative_verb_or_adjective"],
]);